#!/usr/bin/env bash

readonly _here=$(cd "$(dirname "${BASH_SOURCE[0]:-$PWD}")" 2>/dev/null 1>&2 && pwd)

# shellcheck source=/dev/null
. "$_here/source/cli-tooling/build/base-build.sh"

destination="$_here/bin/bootstrap"
if [ ! -d "$destination" ]; then
  mkdir -p "$destination"
fi

destination="$destination/builder"

dc-tools::build::header "$destination" "bootstrap builder" "MIT License" "dubo-dubon-duponey"

for k in "$_here/source/core/"*.sh; do
  dc-tools::build::append "$k" "$destination"
done

for k in "$_here/source/cli-tooling/build/"*.sh; do
  dc-tools::build::append "$k" "$destination"
done

chmod u+x "$destination"
