#!/usr/bin/env bash

readonly _here=$(cd "$(dirname "${BASH_SOURCE[0]:-$PWD}")" 2>/dev/null 1>&2 && pwd)

# shellcheck source=source/cli-tooling/build/base-build.sh
. "$_here/source/cli-tooling/build/base-build.sh"

destination="${1:-$_here}/bin/bootstrap"

[ -d "$destination" ] || mkdir -p "$destination"

destination="$destination/builder"

dc-tooling::build::header "$destination" "bootstrap builder" "MIT License" "dubo-dubon-duponey"

for k in "$_here/source/core/"*.sh; do
  dc-tooling::build::append "$k" "$destination"
done

for k in "$_here/source/cli-tooling/build/"*.sh; do
  dc-tooling::build::append "$k" "$destination"
done

chmod u+x "$destination"
