#!/usr/bin/env bash

_here=$(cd "$(dirname "${BASH_SOURCE[0]:-$PWD}")" 2>/dev/null 1>&2 && pwd)
# shellcheck source=$_here/source/tooling/assert.sh
. "$_here/source/tooling/assert.sh"
# shellcheck source=/dev/null
. "$_here/source/tooling/shellcheck.sh"


tests::run::integration(){
  # Source useful constants from the source code (mainly for exit codes and manifest media types
  # shellcheck source=/dev/null
  . "$_here/source/core/errors.sh"
  # shellcheck source=/dev/null
  . "$_here/source/cli/**/errors.sh"

  # Run all tests
  local allTests=$(ls "$_here/tests/integration/"**/*.sh)
  for i in "$allTests"; do
    printf "%s\n" "Running integration test suite: $i"
    # shellcheck source=/dev/null
    . "$i"
  done
}

tests::run::unit(){
  # Force a fresh build
  local k
  for k in "$_here/source/core"/*.sh; do
    # shellcheck source=/dev/null
    . "$k"
  done

  for k in "$_here/source/extensions"/**/*.sh; do
    # shellcheck source=/dev/null
    . "$k"
  done

  # Run all tests
  local allTests=( $(ls "$_here/tests/unit/"*.sh) )
  for i in "${allTests[@]}"; do
    printf "%s\n" "Running unit test suite: $i"
    # shellcheck source=/dev/null
    . "$i"
  done
}

# Force a fresh build
# $_here/build

dc-tools::sc::install
dc-tools::sc::run


tests::run::unit
# tests::run::integration
